networks:
  users_net:
    driver: bridge
  tasks_net:
    driver: bridge
  schedule_net:
    driver: bridge
  kafka_net:
    driver: bridge
  gateway_net:
    driver: bridge

services:
  # Настройка Api Gateway
  dnevnik.apigateway:
    container_name: gateway
    build:
      context: ./api-gateway
      dockerfile: ./src/Dnevnik.ApiGateway/Dockerfile
    ports:
      - "5002:8080"
    networks:
      - gateway_net
  
  # Настройка микросервиса домашних заданий
  tasks-ms: # Микросервис домашних заданий
    restart: unless-stopped
    container_name: tasks-ms
    build: ./tasks-ms
    ports:
      - "5003:8090"
    volumes:
      - ./tasks-ms-config/config:/etc/task
    networks:
      - tasks_net
      - kafka_net
      - gateway_net
    depends_on:
      - tasks-db
      - kafka
  tasks-db: # БД микросервиса домашних заданий
    image: docker.io/bitnami/postgresql:16
    user: root
    ports:
      - "5433:5432"
    volumes:
      - ./tasks-ms/data/postgres:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - tasks_net
  
  # Настройка микросервиса пользователей
  users-ms:
    container_name: users-ms
    build: ./users-ms
    ports:
      - "5004:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@users-db:5432/user_api
    networks:
      - users_net
      - kafka_net
      - gateway_net
    depends_on:
      - users-db
      - kafka
  users-db:
    image: postgres:16-alpine
    
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: user_api
    volumes:
      - ./users-ms/pgdata:/var/lib/postgresql/data
      - ./users-ms/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5434:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - users_net
  
  # Настройка микросервиса уроков
  schedule-ms:
    container_name: schedule-ms
    ports:
      - "5005:8080"
      - "5006:8001"
    environment:
      - ASPNETCORE_HTTPS_PORTS=8001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
    stdin_open: true
    tty: true
    build:
      context: ./schedule-ms
      dockerfile: ../schedule-ms-Dockerfile
    networks:
      - schedule_net
      - gateway_net
      - kafka_net
    depends_on:
      - schedule-db
      - kafka
  schedule-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./schedule-ms/pgdata:/var/lib/postgresql/data
      - ./schedule-ms/init.sql:/init.sql
    ports:
      - 5435:5432
    networks:
      - schedule_net
        
  # Настройка кафки
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: >-
        events.task:1:1
    ports:
      - 9092:9092
    expose:
      - 9093
      - 9092
    volumes:
      - ./kafka/kafkadata:/kafka
    networks:
      - kafka_net    
  zookeeper:
    image: zookeeper:latest
    ports:
      - 2181:2181
    volumes:
      - ./kafka/zkdata:/data
      - ./kafka/zkdatalog:/datalog
      - ./kafka/zklogs:/logs
    networks:
      - kafka_net
